name: Daily User Stats Update

on:
  schedule:
    # 1) 매일 UTC 14:55 (KST 23:55) - 앱 미리 깨우기 (Pre-ping)
    - cron: "55 14 * * *"
    # 2) 매일 UTC 14:59 (KST 23:59) - 실제 /update-daily
    - cron: "59 14 * * *"

jobs:
  # -----------------------
  # (A) 23:55 KST (UTC 14:55) → Pre-warm
  # -----------------------
  pre_ping:
    runs-on: ubuntu-latest
    # 이 job은 schedule 문자열에 "55 14"가 포함된 경우에만 실행
    if: contains(github.event.schedule, '55 14 * * *')
    steps:
      - name: Pre-warm the Render app
        run: |
          echo "[Actions] Pre-ping at 23:55 KST"
          curl -m 15 https://mafapi.onrender.com/ping || true

  # -----------------------
  # (B) 23:59 KST (UTC 14:59) → /update-daily
  # -----------------------
  update_daily:
    runs-on: ubuntu-latest
    # 이 job은 schedule 문자열에 "59 14"가 포함된 경우에만 실행
    if: contains(github.event.schedule, '59 14 * * *')
    steps:
      - name: Update Daily Endpoint
        run: |
          echo "[Actions] Now calling /update-daily"
          curl -X POST https://mafapi.onrender.com/update-daily
